sudo: false
language: python
python:
    - "2.7"
    - "2.6"
before_install:
    - git config --global user.email "OpenStack_TravisCI@f5.com"
    - git config --global user.name "Travis F5 Openstack"
    - git fetch --depth=100
    - wget https://github.com/F5Networks/f5-icontrol-rest-python/archive/v0.1.0.tar.gz -O /tmp/icontrol.tar.gz
    - tar -zxf /tmp/icontrol.tar.gz -C /tmp
    - mv /tmp/f5-icontrol-rest-python-0.1.0/icontrol/ .
install:
    - pip install hacking pytest pytest-cov
    - pip install -r requirements.txt
script:
    - flake8 .
    - py.test --cov .
notifications:
    slack:
      rooms:
        - f5openstackdev:IbC9KXz2vGVq9jkOLCT5USYD#f5-common-python
        - f5openstackdev:IbC9KXz2vGVq9jkOLCT5USYD#build-status
      on_success: change
      on_failure: always
